### ISSUE TITLE
expand filter if applied

### ISSUE THREAD

**Issue by christoball** [TNRIS/dataHub#192]
In this example: https://data.tnris.org/catalog/%7B%22filters%22%3A%7B%22availability%22%3A%5b%22External_Link%22%5d%7D%7D

When landing it's not visible that 'external link' filter is applied.

Can this be expanded so user knows exactly what's applied?

**Comment by JasonKleinert** [comment]
I think this will be more clear if we add pills to the top of the view for each filter that is applied. We can use [https://material.io/design/components/chips.html#usage](https://material.io/design/components/chips.html#usage). These can each be the dismissible type, so that if you close one here it will also remove that filter. I think this will help draw attention to which filters have been set.

**Comment by jwhaney** [comment]
closed via PR #213
