### ISSUE TITLE
Tiles not drawing

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/dataHub#202]
some tiles for larger collection not drawing. 

open the console. i'm seeing it only on datasets with statewide qquad downloads. console reads error aoubt too many requests which ultimately creates a layer issue (red error in console is missing layer which never got created from the too many requests rejection).
no, i don't immediately think its  a pagination issue, i think its related to carto and the way by which we are retrieving all the vector tiles from carto.
 
Orc
i briefly got that error showing carto too many requests or something similar in the console. i refreshed and didn't experience the errors again... that is for the naip '16 collection.
 
FuryFinale
make an issue in the datahub repo, ryan?
the inconsistency and error is related to the way the layers are requested from carto, not the pagination. probably related to issue #39

**Comment by JasonKleinert** [comment]
@mitchellryant I will most likely address this issue with planned updates to the download map. I have been seeing these errors in the console as well. I will update the issue once a solution has been implemented.

**Comment by adambreznicky** [comment]
Issue 39 idea from carto Dev was to just get all areas layers/features from carto on initial app load and then just use them out of the store client side. Alternative solution idea is to load all the carto layer requests into a promise array and use promises to handle the requests/responses. If the repetitive nature of the series of requests is tripping up in timing so many consecutively, promises might handle the situation more reliably. Just a thought

**Comment by adambreznicky** [comment]
updated the areas chunk iterator for retrieving from carto to use 2000 records per request rather than 1000. this cuts the carto api request count in half. testing now, the error i gone. 
resolved 1cc69c7d6ddda99b6b843b159e672cc48615e6eb

now that our mapserver is serving vector tiles, we should consider reworking the download map to use our own hosted download areas and get rid of carto. at that time, we could rework the general on-load bootstrapping to pre-load into the store at app load rather than download map load.
