### ISSUE TITLE
Zoom in level on statewide too close

### ISSUE THREAD

**Issue by christoball** [TNRIS/dataHub#210]
@jwhaney @JasonKleinert @adambreznicky 

When using the Download on the NAIP 2018, the zoom level is locked at a level which makes it difficult to orient yourself, just filling the screen with gray boxes. Zooming out is not possible, forcing people to have to pan the map zoomed in.

For statewide datasets, the zoom should be set at a level that generally shows the whole state (obviously depends on the device) to first to allow people orient themselves and then find their desired location.

![image](https://user-images.githubusercontent.com/1877550/66349619-e7dfb800-e91e-11e9-8d4c-43dd96f5f1f3.png)

**Comment by jwhaney** [comment]
This is intentional for download maps with qquads shown. The dataset should default to the county map like the NAIP 2016 but the 2018 does not seem to have the counties available. This could be something that was missed when the new dataset was set up? I'm not sure. 

@adambreznicky @mitchellryant do yall have suggestions as to why the counties are not available for the new 2018 NAIP?

**Comment by jwhaney** [comment]
closing this issue now since we have future enhancement plans to address the map.
