### ISSUE TITLE
Adding Scan Status Filter for Historical Collections

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/dataHub#270]
Howdy IS,

RDC requests a filter function for all historical collections with a scanned status of "complete".  Recent changes to Lore, have potentially fast-tracked the opportunity to move consultants out of Lore altogether.  It would be beneficial to consultants/general public to be able to quickly filter completely scanned collections through DataHub.

Let me know if I can provide more information!

**Comment by adambreznicky** [comment]
as per teams meeting, we will no longer be catering to consultants as clients separate from the general public so the ultimate goal will be that all completed collections will eventually migrate into LCD (standard collections), at which point a filter will exist by utilizing the pre-existing "Download" filter. closing this issue since no immediate or consultant specific enhancements will be happening
